name: Deploy to Fleek

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    name: A job to test the action-deploy action by deploying a test site
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Creates optimized production build
        run: yarn build
      - name: Export build to static HTML
        run: yarn export
      - name: Deploy application to Fleek
        id: deploy
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
      - name: Get the output url
        run: echo "Deploy url is ${{ steps.deploy.outputs.deployUrl }}"
